Smoothboard Stylers/Smoothboard Stylers/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Smoothboard_Stylers.Data;
using Smoothboard_Stylers.Factories;
using Smoothboard_Stylers.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net.Mail;
using System.Threading.Tasks;

namespace Smoothboard_Stylers.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly Smoothboard_StylersContext _context;
        public readonly MailTaskFactory _mailTaskFactory;

        public HomeController(ILogger<HomeController> logger, Smoothboard_StylersContext context, MailTaskFactory mailTaskFactory)
        {
            _logger = logger;
            _context = context;
            _mailTaskFactory = mailTaskFactory;
        }

        public IActionResult Index()
        {
            if (TempData["ec"] != null)
            {
                var ec = (object[])TempData["ec"];
                ViewBag.Status = ec[1];
                ViewBag.StatusMessage = ec[0];
            }

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult RedirectTest()
        {
            TempData["ec"] = MyExtentions.GetEc("TestS");
            return RedirectToAction("Index", "Home");
        }

        public IActionResult Contact()
        {
            if (TempData["ec"] != null)
            {
                var ec = (object[])TempData["ec"];
                ViewBag.Status = ec[1];
                ViewBag.StatusMessage = ec[0];
            }

            return View();
        }

        [HttpPost]
        public IActionResult ContactMail(string firstname, string lastname, string email, string phone, string message)
        {
            if(string.IsNullOrEmpty(firstname) || string.IsNullOrEmpty(lastname) || string.IsNullOrEmpty(email) || string.IsNullOrEmpty(phone) || string.IsNullOrEmpty(message))
            {
                TempData["ec"] = MyExtentions.GetEc("FormEmpty");
                return RedirectToAction("Contact", "Home");
            }

            string msg = "Dear Mr/Mrs, \n You recieved a mail from Smoothboard Stylers by " + firstname + " " + lastname + ". \n Email: " + email + "\n Tel: " + phone + "\n " + message;

            _mailTaskFactory.CreateCustomMailTasks("Smoothboard Stylers Website Contact", msg, new MailAddress("colin.bloemendaal@gmail.com"), false);

            TempData["ec"] = MyExtentions.GetEc("ContactFormSend");
            return RedirectToAction("Contact", "Home");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Smoothboard Stylers/Smoothboard Stylers/Controllers/NewsletterController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Mvc;
using Smoothboard_Stylers.Data;
using Smoothboard_Stylers.Factories;
using Smoothboard_Stylers.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Smoothboard_Stylers.Controllers
{
    public class NewsletterController : Controller
    {
        public readonly Smoothboard_StylersContext _context;

        public NewsletterController(Smoothboard_StylersContext context)
        {
            _context = context;
        }

        [HttpPost]
        public IActionResult AddSubscriber(string Name, string Email)
        {
            _context.NewsletterSubscribers.Add(new NewsletterSubscriber() { Name = Name, Email = Email });
            _context.SaveChanges();

            return RedirectToAction("Index", "Home");
        }
    }
}

Smoothboard Stylers/Smoothboard Stylers/Views/Home/Contact.cshtml
<div class="wrap-contact100">
    <form class="contact100-form validate-form" asp-action="ContactMail" asp-controller="Home">
        <span class="contact100-form-title">
            Send Us A Message
        </span>

        <label class="label-input100" for="first-name">Tell us your name *</label>
        <div class="wrap-input100 rs1-wrap-input100 validate-input" data-validate="Type first name">
            <input id="first-name" class="input100" type="text" name="firstname" placeholder="First name">
            <span class="focus-input100"></span>
        </div>
        <div class="wrap-input100 rs2-wrap-input100 validate-input" data-validate="Type last name">
            <input class="input100" type="text" name="lastname" placeholder="Last name">
            <span class="focus-input100"></span>
        </div>

        <label class="label-input100" for="email">Enter your email *</label>
        <div class="wrap-input100 validate-input" data-validate="Valid email is required: ex@abc.xyz">
            <input id="email" class="input100" type="text" name="email" placeholder="Eg. example@email.com">
            <span class="focus-input100"></span>
        </div>

        <label class="label-input100" for="phone">Enter phone number</label>
        <div class="wrap-input100">
            <input id="phone" class="input100" type="text" name="phone" placeholder="Eg. +1 800 000000">
            <span class="focus-input100"></span>
        </div>

        <label class="label-input100" for="message">Message *</label>
        <div class="wrap-input100 validate-input" data-validate="Message is required">
            <textarea id="message" class="input100" name="message" placeholder="Write us a message"></textarea>
            <span class="focus-input100"></span>
        </div>

        <div class="container-contact100-form-btn">
            <button class="contact100-form-btn">
                Send Message
            </button>
        </div>
    </form>

    
</div>

Smoothboard Stylers/Smoothboard Stylers/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="col-md-3 float-right border border-info rounded-sm p-3">
    <h2>Newsletter</h2>
    <h4>Subscribe right now!</h4>
    <form method="post" asp-action="AddSubscriber" asp-controller="Newsletter">
        <div class="form-group">
            <label for="nameInput">Name</label>
            <input type="text" class="form-control" name="Name" id="nameInput" />
        </div>
        <div class="form-group">
            <label for="emailInput">Email</label>
            <input type="email" class="form-control" name="Email" id="emailInput" />
        </div>
        <button type="submit" class="mt-3 btn btn-outline-info">Subscribe!</button>
    </form>
</div>