Smoothboard Stylers/Smoothboard Stylers/Controllers/FAQController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Smoothboard_Stylers.Areas.Identity.Data;
using Smoothboard_Stylers.Data;
using Smoothboard_Stylers.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Smoothboard_Stylers.Controllers
{
    public class FAQController : Controller
    {
        private readonly Smoothboard_StylersContext _context;

        public FAQController(Smoothboard_StylersContext context)
        {
            _context = context;
        }

        public IActionResult FAQ()
        {
            if (TempData["ec"] != null)
            {
                var ec = (object[])TempData["ec"];
                ViewBag.Status = ec[1];
                ViewBag.StatusMessage = ec[0];
            }
            int page = 1;
            if (!string.IsNullOrEmpty(HttpContext.Request.Query["Page"]))
                page = Int32.Parse(HttpContext.Request.Query["Page"]);


            var FAQs = _context.FAQs.GetPaged(page, 15);
            if (FAQs == null)
            {
                TempData["ec"] = MyExtentions.GetEc("FAQEmpty");
                return RedirectToAction("Index", "Home");
            }
            ViewBag.CurrentPage = page;
            return View(FAQs);
        }
    }
}

Smoothboard Stylers/Smoothboard Stylers/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Smoothboard_Stylers</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/Articles.css" />
    <link rel="stylesheet" href="~/css/contact.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Smoothboard_Stylers</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Shop" asp-action="Index">Shop</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="FAQ" asp-action="FAQ">FAQ</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @{
                if (!string.IsNullOrWhiteSpace(ViewBag.StatusMessage) && !string.IsNullOrWhiteSpace(ViewBag.Status))
                {
                    <div class="form-group">
                        <input type="text" class="form-control @if (ViewBag.Status == "Succes") { <text>is-valid</text> } else if (ViewBag.Status == "Info") { <text></text> } else if (ViewBag.Status == "Warning") { <text>is-invalid</text> }" placeholder="@ViewBag.StatusMessage" disabled>
                    </div>
                }
            }
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted mt-lg-3">
        <div class="container">
            &copy; 2021 - Smoothboard_Stylers - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>